server:
  port: 8001
spring:
  cloud:
    sentinel:
      enabled: true # sentinel开关
      eager: true
      transport:
        dashboard: localhost:8080 # Sentinel控制台地址
        port: 8719
        client-ip: localhost
    nacos:
      # 注册中心
      discovery:
        server-addr: http://localhost:8848
      # 配置中心
      config:
        group: DEFAULT_GROUP
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - optional:nacos:gateway-dev.yml?group=DEFAULT_GROUP&refreshEnabled=true

# Sentinel
sentinel:
  dashboard: localhost:7999

